stages:
  - generateAndBuild

variables:
  CMAKE_GENERATOR: "Ninja"

image: kavalchuk.d.v/my-runner

buildMiniSpaceSimulator:
  stage: generateAndBuild
  script:
    - mkdir build
    - cd build
    - cmake ..
    - cmake --build .
