stages:
  - generateAndBuild

variables:
  CMAKE_GENERATOR: "Ninja"

image: kavalchukd/fedora_latest

buildMiniSpaceSimulator:
  stage: generateAndBuild
  script:
    - mkdir build
    - cd build
    - cmake ..
    - cmake --build .
