stages:
  - generateBuildRun

variables:
  CMAKE_GENERATOR: "Ninja"

image: leanid/fedora_latest

generateGdt:
  stage: generateBuildRun
  script:
    - cmake .
    - cmake --build .
    - ./game/mini-space-simulator
