stages:
  - generateBuildRun

variables:
  CMAKE_GENERATOR: "Ninja"

image: leanid/fedora_latest

generateGdt:
  stage: generateBuildRun
  script:
    - mkdir build
    - cd build
    - cmake ..
    - cmake --build .
